1.	Write a Python Program to Add Two Matrices?

In [4]:
import numpy as np
  
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
  
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
 
result = np.array(X) + np.array(Y)
 
print(result)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


2.	Write a Python Program to Multiply Two Matrices?

In [7]:
import numpy as np
 
# input two matrices
mat1 = [[1, 6, 5],
        [3 ,4, 8],
        [2, 12, 3]]

mat2 = [[3, 4, 6],
        [5, 6, 7],
        [6,56, 7]]
 
# This will return matrix product of two array
res =np.array(mat1) @ np.array(mat2)
 
# print resulted matrix
print(res)

[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


3.	Write a Python Program to Transpose a Matrix?

In [8]:
import numpy as np
mat1 = [[1, 6, 5],
        [3 ,4, 8],
        [2, 12, 3]]

a=np.matrix(mat1)
print(a.transpose())

[[ 1  3  2]
 [ 6  4 12]
 [ 5  8  3]]


4.	Write a Python Program to Sort Words in Alphabetic Order?

In [14]:
str="today is a good day to live"
words=str.split(' ')
words.sort()
print(words)

['a', 'day', 'good', 'is', 'live', 'to', 'today']


5.	Write a Python Program to Remove Punctuation From a String?

In [2]:
import re

test_string='!hi.How are you ?//?'
new_string=re.sub(r'[^\w\s]',' ',test_string)

print(new_string)



 hi How are you     
