In [ ]:
Question 1:

Write a program that calculates and prints the value according to the given formula:

Q = Square root of [(2 * C * D)/H]

Following are the fixed values of C and H:

C is 50. H is 30.

D is the variable whose values should be input to your program in a comma-separated sequence.

Example

Let us assume the following comma separated input sequence is given to the program:

100,150,180

The output of the program should be:

18,22,24


In [42]:
import numpy as np
#define program1
def program1(*D):
    
    #fixed values
    C=50;H=30 
    
    #calculate Q
    Q=tuple(int(np.round(np.sqrt((2*C*d)/H))) for d in D)
   
    
    #print input and output
    print("Given input : ",D)
    print("Calculated output : ",Q)
    
    
if __name__=="__main__":
    program1(100,150,180)

Given input :  (100, 150, 180)
Calculated output :  (18, 22, 24)


In [ ]:
Question 2:
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.

Note: i=0,1.., X-1; j=0,1,¡¬Y-1.

Example

Suppose the following inputs are given to the program:

3,5

Then, the output of the program should be:

[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]] 


In [33]:
def program2(X,Y):
    array=np.empty((X,Y),dtype=int)
    for i in range(X):
        for j in range(Y):
            array[i][j]=i*j
             
    print(array)

    
if __name__=="__main__":
    program2(3,5)

[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


In [ ]:
Question 3:
Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.

Suppose the following input is supplied to the program:

without,hello,bag,world

Then, the output should be:

bag,hello,without,world


In [43]:
def program3(*words):
    list_words=[*words]
    list_words.sort()
    print(",".join(list_words))

if __name__=="__main__": 
    program3('without','hello','bag','world')

bag,hello,without,world


In [ ]:
Question 4:
Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

Suppose the following input is supplied to the program:

hello world and practice makes perfect and hello world again

Then, the output should be:

again and hello makes perfect practice world


In [46]:
def program4(string):
    words=string.split(' ')
    unique_words=set(words)   #removes duplicates
    sorted_words=sorted(unique_words) #sorts words in alphebetical order
    print(" ".join(sorted_words))    #print final result
    
    
if __name__=="__main__": 
    program4('hello world and practice makes perfect and hello world again')
    

again and hello makes perfect practice world


In [ ]:
Question 5:
Write a program that accepts a sentence and calculate the number of letters and digits.

Suppose the following input is supplied to the program:

hello world! 123

Then, the output should be:

LETTERS 10

DIGITS 3


In [52]:
import re

def program5(sentence):
    number_of_letters=0
    number_of_digits=0
    
    #using regular expressions  for digits and letters
    digits=re.compile(r'[0-9]')
    letters=re.compile(r'[a-zA-Z]')
    
    digits_list=digits.findall(sentence)
    letters_list=letters.findall(sentence)
    
    #print the count
    print("LETTERS ",len(letters_list) )  
    print("DIGITS ",len(digits_list))
    
    
if __name__=="__main__": 
    program5('hello world! 123')
    
    

LETTERS  10
DIGITS  3


In [ ]:
Question 6:
A website requires the users to input username and password to register. Write a program to check the validity of password input by users.

Following are the criteria for checking the password:

1. At least 1 letter between [a-z]

2. At least 1 number between [0-9]

1. At least 1 letter between [A-Z]

3. At least 1 character from [$#@]

4. Minimum length of transaction password: 6

5. Maximum length of transaction password: 12

Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma.

Example

If the following passwords are given as input to the program:

ABd1234@1,a F1#,2w3E*,2We3345

Then, the output of the program should be:

ABd1234@1


In [33]:
import re 
regex = r"^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[$#@]).{6,12}$"
pwd='ABd1234@1'
if re.fullmatch(regex,pwd):
    print("Valid")
else:
    print("Invalid")

Valid


In [43]:
import re 

def check_password(passwords):
    
    regex = r"^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[$#@]).{6,12}$"
    list_pwd=passwords.split(',')
    valid_passwords=[]
    for pwd in list_pwd:
        if re.fullmatch(regex,pwd):
            valid_passwords.append(pwd)
            
    print("Below are valid passwords: ")
    for pwd in valid_passwords:
        print(pwd)



passwords=r'ABd1234@1,a F1#,2w3E*,2We3345'
check_password(passwords)

Below are valid passwords: 
ABd1234@1
