1.	Write a Python Program to find sum of array?

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print("Array is : ",arr)
sum_of_elements=np.sum(arr)
print("Sum of elements in array is : ",sum_of_elements)

Array is :  [1 2 3 4 5 6]
Sum of elements in array is :  21


2.	Write a Python Program to find largest element in an array?

In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
largest_element=np.max(arr)
print("Array is : ",arr)
print("Largest element in the array is :",largest_element)


Array is :  [1 2 3 4 5 6]
Largest element in the array is : 6


3.	Write a Python Program for array rotation?

In [6]:
import numpy as np
array=np.arange(12).reshape(3,4)
print("Array before rotation: \n",array)
print("Array after rotation: \n",np.rot90(array))

Array before rotation: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array after rotation: 
 [[ 3  7 11]
 [ 2  6 10]
 [ 1  5  9]
 [ 0  4  8]]


4.	Write a Python Program to Split the array and add the first part to the end?

In [10]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
list_array=np.array_split(arr,2)

print("Original array : ",arr)
print("list of split array : ",list_array)
first_part=list_array[0]
end_part=list_array[1]
print("New array after adding first part to the end : ",np.append(end_part,first_part))


Original array :  [1 2 3 4 5 6]
list of split array :  [array([1, 2, 3]), array([4, 5, 6])]
New array after adding first part to the end :  [4 5 6 1 2 3]


5.	Write a Python Program to check if given array is Monotonic?

In [16]:
"""An array is said to be monotonic in nature if it is either continuously increasing or continuously decreasing."""

def check_monotonic_array(array):
    if (all( array[i] < array[i+1] for i in range(len(array)-1))) or (all( array[i] > array[i+1] for i in range(len(array)-1))):
        print("Given Array is monotonic")
        
    else:
        print("Given Array is not monotonic")

    
array=np.array([8,5,3,2,1])        
check_monotonic_array(array)   
    

Given Array is monotonic
